# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2.2'

volumes:
  data:
  esdata1:

services:
  ###########################
  # Setup the Apache container
  ###########################
  httpd:
    container_name: docker_httpd
    restart: always
    image: httpd:2.4.25
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/vhosts/:/usr/local/apache2/conf/vhosts
    volumes_from:
      - php
    depends_on:
      - php

  ###########################
  # Setup the PHP container
  ###########################
  php:
    container_name: docker_php
    restart: always
    build: ./php/
    expose:
      - 9000
    volumes:
      - ../www:/var/www/html
      - ./php/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro
      - ./php/php-mail.conf:/usr/local/etc/php/conf.d/mail.ini:ro

  ###########################
  # Setup the Database (MySQL) container
  ###########################
  mysql:
    container_name: docker_mysql
    restart: always
    hostname: mysql
    image: mysql:5.7
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/conf-mysql.cnf:/etc/mysql/mysql.conf.d/conf-mysql.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: 'dbname'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'secret'

  ###########################
  # Setup the Php myadmin
  ###########################
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - mysql:mysql
    environment:
      PMA_HOSTS: mysql

      ###########################
      # Setup the Blackfire container
      ###########################
      #blackfire:
      #image: blackfire/blackfire
      #environment:
      #Exposes the host BLACKFIRE_SERVER_ID and TOKEN environment variables.
      #BLACKFIRE_SERVER_ID: a0073950-08bc-4e84-9f8b-c2d99b9361fd
      #BLACKFIRE_SERVER_TOKEN: c7e6406cd8b36db18a897e39ebc76ab676dfb923c701ec011ed08ead10185b78
      # You can also use global environment credentials :
      # BLACKFIRE_SERVER_ID: SERVER-ID
      # BLACKFIRE_SERVER_TOKEN: SERVER-TOKEN

  ###########################
  # Setup the Elastic Search container
  ###########################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      # volumes:
      # - ./data/esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    hostname: elasticsearch

  #######################
  # Setup Mailhog
  #######################
  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui